# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-iso:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
    - name: "Get repo"
      run: git clone https://github.com/KeDRome/debpreseed.git repo
    - name: "Make iso with script"
      run: cd ./repo && sudo sh ./makeiso.sh
  run-vm:
    runs-on: self-hosted
    needs: build-iso
    steps:
    - name: "Run installation with virt-install"
      run: |
        sudo virt-install \
          --cdrom /storage/iso/auto_debian11.iso \
          --memory 4096 \
          --disk /storage/disk.qcow2 \
          --name debpreseed \
          --check path_in_use=off

  clear-tmps:
    runs-on: self-hosted
    needs: build-iso
    steps:
    - name: "Clear downloaded repo dir"
      run: sudo rm -rf ./repo
    - name: "Clear .tpm* in /tmp"
      run: sudo rm -rf /tmp/.tmp*

  clear-vm: 
    runs-on: self-hosted
    needs: manual
    steps:
    - name: "Destroy and undefine testing VM"
      run: |
        sudo virsh undefine --domain debpreseed \
        sudo virsh destroy --domain debpreseed